on:
  push:

jobs:
  setup-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Check Rust version
        run: rustc --version
      - name: Check Rust Up version
        run: rustup --version
      - name: Compile Rust to WASM
        run: rustup target add wasm32-unknown-unknown
        
  install-Trunk:
    needs: setup-rust
    runs-on: ubuntu-latest
    steps:
      - name: Install Trunk
        run: cargo install trunk wasm-bindgen-cli
      - name: Install Trunk
        run: cargo install trunk wasm-bindgen-cli
